#3C48 with attenuator
#---------------------
flagdata(vis="42_028_25jun2022.ms",mode="clip",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[0, 100],datacolumn="data",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="0:420;512;536",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="0:420;507;512",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="clip",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[0, 20],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="tfcrop",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=3,flagdimension="freqtime",usewindowstats="none",halfwin=3,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="16",uvrange="",timerange="03:04:30~03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="0:537",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="16&17",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="16&18",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="17&18",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

#First round calibration
#-----------------------
clearcal(vis='42_028_25jun2022.ms')

setjy(vis="42_028_25jun2022.ms",field="1",spw="",selectdata=True,timerange="",scan="",intent="",observation="",scalebychan=True,standard="Perley-Butler 2017",model="",modimage=None,listmodels=False,fluxdensity=-1,spix=0.0,reffreq="1GHz",polindex=[],polangle=[],rotmeas=0.0,fluxdict={},useephemdir=False,interpolation="nearest",usescratch=True,ismms=None)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_att_round1.gcalp",field="1",spw="0:390~410",intent="",selectdata=True,timerange="<03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="p",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=[],gainfield=[],interp=[],spwmap=[],parang=True)

bandpass(vis="42_028_25jun2022.ms",caltable="3C48_att_round1.bcal",field="1",spw="",intent="",selectdata=True,timerange="<03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="inf",combine="",refant="9",minblperant=4,minsnr=3.0,solnorm=False,bandtype="B",smodel=[],corrdepflags=False,append=False,fillgaps=0,degamp=3,degphase=3,visnorm=False,maskcenter=0,maskedge=5,docallib=False,callib="",gaintable=['3C48_att_round1.gcalp'],gainfield=[],interp=[],spwmap=[],parang=True)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_att_round1.gcalap",field="1",spw="",intent="",selectdata=True,timerange="<03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="ap",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=['3C48_att_round1.bcal'],gainfield=[],interp=['nearest,nearestflag'],spwmap=[],parang=True)

applycal(vis="42_028_25jun2022.ms",field="1",spw="",intent="",selectdata=True,timerange="<03:06:00",uvrange="",antenna="",scan="",observation="",msselect="",docallib=False,callib="",gaintable=['3C48_att_round1.bcal', '3C48_att_round1.gcalap'],gainfield=[],interp=['nearest,nearestflag', 'linear'],spwmap=[],calwt=[True],parang=True,applymode="",flagbackup=True)

#Post calibration flagging
#--------------------------
flagdata(vis="42_028_25jun2022.ms",mode="clip",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[0, 200],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="tfcrop",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="residual",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=3,flagdimension="freqtime",usewindowstats="none",halfwin=3,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="03:05:07~03:05:20",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="03:00:40.2563",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="clip",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="<03:06:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[0, 50],datacolumn="residual",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis='42_028_25jun2022.ms',timerange='03:02:40~03:03:10',field='1',mode='manual')

#First round calibration
#-----------------------
clearcal(vis='42_028_25jun2022.ms')

setjy(vis="42_028_25jun2022.ms",field="1",spw="",selectdata=True,timerange="",scan="",intent="",observation="",scalebychan=True,standard="Perley-Butler 2017",model="",modimage=None,listmodels=False,fluxdensity=-1,spix=0.0,reffreq="1GHz",polindex=[],polangle=[],rotmeas=0.0,fluxdict={},useephemdir=False,interpolation="nearest",usescratch=True,ismms=None)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_att_round2.gcalp",field="1",spw="0:390~410",intent="",selectdata=True,timerange="<03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="p",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=[],gainfield=[],interp=[],spwmap=[],parang=True)

bandpass(vis="42_028_25jun2022.ms",caltable="3C48_att_round2.bcal",field="1",spw="",intent="",selectdata=True,timerange="<03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="inf",combine="",refant="9",minblperant=4,minsnr=3.0,solnorm=False,bandtype="B",smodel=[],corrdepflags=False,append=False,fillgaps=0,degamp=3,degphase=3,visnorm=False,maskcenter=0,maskedge=5,docallib=False,callib="",gaintable=['3C48_att_round2.gcalp'],gainfield=[],interp=[],spwmap=[],parang=True)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_att_round2.gcalap",field="1",spw="",intent="",selectdata=True,timerange="<03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="ap",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=['3C48_att_round2.bcal'],gainfield=[],interp=['nearest,nearestflag'],spwmap=[],parang=True)

polcal(vis="42_028_25jun2022.ms",caltable="3C48_round3_att.dfcal",field="1",spw="",intent="",selectdata=True,timerange="<03:06:00",uvrange="",antenna="",scan="",observation="",msselect="",solint="inf",combine="",preavg=-1.0,refant="9",minblperant=6,minsnr=3.0,poltype="Df",smodel=[],append=False,docallib=False,callib="",gaintable=['3C48_att_round2.gcalap/', '3C48_att_round2.bcal/'],gainfield=[],interp=['linear', 'nearest'],spwmap=[])

applycal(vis="42_028_25jun2022.ms",field="1",spw="",intent="",selectdata=True,timerange="<03:06:00",uvrange="",antenna="",scan="",observation="",msselect="",docallib=False,callib="",gaintable=['3C48_att_round2.bcal', '3C48_att_round2.gcalap'],gainfield=[],interp=['nearest,nearestflag', 'linear'],spwmap=[],calwt=[True],parang=True,applymode="",flagbackup=True)


# Chaning attenuator scaling
##############################
tb.open('3C48_round3.bcal')
gain=tb.getcol('CPARAM')
flag=tb.getcol('FLAG')
gain[flag]=np.nan
tb.close()

tb.open('3C48_att_round2.bcal')
gain_att=tb.getcol('CPARAM')
flag_att=tb.getcol('FLAG')
gain_att[flag_att]=np.nan
tb.close()

x=np.abs(gain_att)/np.abs(gain)

del gain,gain_att
os.system('cp -r 3C48_round3.bcal 3C48_round3_att.bcal')
tb.open('3C48_round3_att.bcal',nomodify=False)
gain=tb.getcol('CPARAM')
flag=tb.getcol('FLAG')
gain*=x
gain[np.isnan(gain)]=1.0
flag[np.isnan(gain)]=True
tb.putcol('CPARAM',gain)
tb.putcol('FLAG',flag)
tb.flush()
tb.close()

applycal(vis="42_028_25jun2022.ms",field="3,4,5",spw="",intent="",selectdata=True,timerange="",uvrange="",antenna="",scan="",observation="",msselect="",docallib=False,callib="",gaintable=['3C48_round3_att.bcal/', '3C48_round3_att.dfcal/', '3C48_round3.gcalap/'],gainfield=[],interp=['nearest', 'nearest', 'linear'],spwmap=[],calwt=[True],parang=True,applymode="",flagbackup=True)













