os.system('casa -c flagging_1.py')

#First round calibration
#-----------------------
setjy(vis="42_028_25jun2022.ms",field="1",spw="",selectdata=True,timerange="",scan="",intent="",observation="",scalebychan=True,standard="Perley-Butler 2017",model="",modimage=None,listmodels=False,fluxdensity=-1,spix=0.0,reffreq="1GHz",polindex=[],polangle=[],rotmeas=0.0,fluxdict={},useephemdir=False,interpolation="nearest",usescratch=True,ismms=None)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_round1.gcalp",field="1",spw="0:390~410",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="p",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=[],gainfield=[],interp=[],spwmap=[],parang=True)

bandpass(vis="42_028_25jun2022.ms",caltable="3C48_round1.bcal",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="inf",combine="",refant="9",minblperant=4,minsnr=3.0,solnorm=True,bandtype="B",smodel=[],corrdepflags=False,append=False,fillgaps=0,degamp=3,degphase=3,visnorm=False,maskcenter=0,maskedge=5,docallib=False,callib="",gaintable=['3C48_round1.gcalp'],gainfield=[],interp=[],spwmap=[],parang=True)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_round1.gcalap",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="ap",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=['3C48_round1.bcal'],gainfield=[],interp=[],spwmap=[],parang=True)

applycal(vis="42_028_25jun2022.ms",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange="",antenna="",scan="",observation="",msselect="",docallib=False,callib="",gaintable=['3C48_round1.bcal', '3C48_round1.gcalap'],gainfield=[],interp=['nearest,nearestflag', 'nearest,nearestflag'],spwmap=[],calwt=[True],parang=True,applymode="",flagbackup=True)


#Post calibration flagging 1
#----------------------------
flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="03:06:00~03:08:30",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="manual",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange="03:10:50~03:11:00",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)


flagdata(vis="42_028_25jun2022.ms",mode="clip",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange=">03:12:36",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[0, 1000],datacolumn="residual",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="tfcrop",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange=">03:12:36",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="residual",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=3,flagdimension="freqtime",usewindowstats="none",halfwin=3,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis='42_028_25jun2022.ms',field='1',mode='manual',timerange='>03:12:36',spw='0:420')

flagdata(vis="42_028_25jun2022.ms",mode="tfcrop",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange=">03:12:36",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="residual",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=3,flagdimension="freqtime",usewindowstats="none",halfwin=3,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

for i in range(0,17,2):
	flagdata(vis='42_028_25jun2022.ms',field='1',timerange='>03:12:36',mode='tfcrop',uvrange=str(i)+'~'+str(i+2)+'klambda',datacolumn='residual',maxnpieces=3,halfwin=3)

flagdata(vis="42_028_25jun2022.ms",mode="clip",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange=">03:12:36",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[0, 200],datacolumn="residual",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

for i in range(30):
       flagdata(vis='42_028_25jun2022.ms',field='1',timerange='>03:12:36',mode='rflag',antenna=str(i+1),datacolumn='residual',maxnpieces=3,halfwin=3) 

flagdata(vis="42_028_25jun2022.ms",mode="extend",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange=">03:08:30",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=80.0,growfreq=80.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)


#Second round calibration
#-----------------------
clearcal(vis='42_028_25jun2022.ms')

setjy(vis="42_028_25jun2022.ms",field="1",spw="",selectdata=True,timerange="",scan="",intent="",observation="",scalebychan=True,standard="Perley-Butler 2017",model="",modimage=None,listmodels=False,fluxdensity=-1,spix=0.0,reffreq="1GHz",polindex=[],polangle=[],rotmeas=0.0,fluxdict={},useephemdir=False,interpolation="nearest",usescratch=True,ismms=None)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_round2.gcalp",field="1",spw="0:390~410",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="p",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=[],gainfield=[],interp=[],spwmap=[],parang=True)

bandpass(vis="42_028_25jun2022.ms",caltable="3C48_round2.bcal",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="inf",combine="",refant="9",minblperant=4,minsnr=3.0,solnorm=True,bandtype="B",smodel=[],corrdepflags=False,append=False,fillgaps=0,degamp=3,degphase=3,visnorm=False,maskcenter=0,maskedge=5,docallib=False,callib="",gaintable=['3C48_round2.gcalp'],gainfield=[],interp=[],spwmap=[],parang=True)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_round2.gcalap",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="ap",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=['3C48_round2.bcal'],gainfield=[],interp=[],spwmap=[],parang=True)

applycal(vis="42_028_25jun2022.ms",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange="",antenna="",scan="",observation="",msselect="",docallib=False,callib="",gaintable=['3C48_round2.bcal', '3C48_round2.gcalap'],gainfield=[],interp=['nearest,nearestflag', 'nearest,nearestflag'],spwmap=[],calwt=[True],parang=True,applymode="",flagbackup=True)

#Post calibration flag 2
#------------------------
flagdata(vis="42_028_25jun2022.ms",mode="clip",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange=">03:06:30",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[0, 100],datacolumn="residual",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=50.0,growfreq=50.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis="42_028_25jun2022.ms",mode="extend",autocorr=False,inpfile="",reason="any",tbuff=0.0,spw="",field="1",antenna="",uvrange="",timerange=">03:06:30",correlation="",scan="",intent="",array="",observation="",feed="",clipminmax=[],datacolumn="DATA",clipoutside=True,channelavg=False,chanbin=1,timeavg=False,timebin="0s",clipzeros=False,quackinterval=1.0,quackmode="beg",quackincrement=False,tolerance=0.0,addantenna="",lowerlimit=0.0,upperlimit=90.0,ntime="scan",combinescans=False,timecutoff=4.0,freqcutoff=3.0,timefit="line",freqfit="poly",maxnpieces=7,flagdimension="freqtime",usewindowstats="none",halfwin=1,extendflags=True,winsize=3,timedev="",freqdev="",timedevscale=5.0,freqdevscale=5.0,spectralmax=1000000.0,spectralmin=0.0,antint_ref_antenna="",minchanfrac=0.6,verbose=False,extendpols=True,growtime=80.0,growfreq=80.0,growaround=False,flagneartime=False,flagnearfreq=False,minrel=0.0,maxrel=1.0,minabs=0,maxabs=-1,spwchan=False,spwcorr=False,basecnt=False,fieldcnt=False,name="Summary",action="apply",display="",flagbackup=True,savepars=False,cmdreason="",outfile="",overwrite=True,writeflags=None)

flagdata(vis='42_028_25jun2022.ms',mode='manual',spw='0:419~420',field='1'timerange='>03:06:00')

#Third round calibration
#-----------------------
clearcal(vis='42_028_25jun2022.ms')

setjy(vis="42_028_25jun2022.ms",field="1",spw="",selectdata=True,timerange="",scan="",intent="",observation="",scalebychan=True,standard="Perley-Butler 2017",model="",modimage=None,listmodels=False,fluxdensity=-1,spix=0.0,reffreq="1GHz",polindex=[],polangle=[],rotmeas=0.0,fluxdict={},useephemdir=False,interpolation="nearest",usescratch=True,ismms=None)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_round3.gcalp",field="1",spw="0:390~410",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="p",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=[],gainfield=[],interp=[],spwmap=[],parang=True)

bandpass(vis="42_028_25jun2022.ms",caltable="3C48_round3.bcal",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="inf",combine="",refant="9",minblperant=4,minsnr=3.0,solnorm=True,bandtype="B",smodel=[],corrdepflags=False,append=False,fillgaps=0,degamp=3,degphase=3,visnorm=False,maskcenter=0,maskedge=5,docallib=False,callib="",gaintable=['3C48_round3.gcalp'],gainfield=[],interp=[],spwmap=[],parang=True)

gaincal(vis="42_028_25jun2022.ms",caltable="3C48_round3.gcalap",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange=">2klambda",antenna="",scan="",observation="",msselect="",solint="10s",combine="",preavg=-1.0,refant="9",refantmode="strict",minblperant=4,minsnr=3.0,solnorm=False,normtype="mean",gaintype="G",smodel=[],calmode="ap",solmode="R",rmsthresh=[10, 7, 5, 3.5],corrdepflags=False,append=False,splinetime=3600.0,npointaver=3,phasewrap=180.0,docallib=False,callib="",gaintable=['3C48_round3.bcal'],gainfield=[],interp=[],spwmap=[],parang=True)

polcal(vis="42_028_25jun2022.ms",caltable="3C48_round3.dfcal",field="1",spw="",intent="",selectdata=True,timerange=">03:06:00",uvrange="",antenna="",scan="",observation="",msselect="",solint="inf",combine="",preavg=-1.0,refant="9",minblperant=6,minsnr=3.0,poltype="Df",smodel=[],append=False,docallib=False,callib="",gaintable=['3C48_round3.gcalap', '3C48_round3.bcal'],gainfield=[],interp=['linear', 'nearest'],spwmap=[])











